# Generated by Django 4.2.1 on 2023-06-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marka",
                    models.CharField(
                        choices=[("lexus", "lexus"), ("toyota", "toyota")], max_length=6
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("rok_produkcji", models.IntegerField()),
            ],
        ),
    ]
